"""migration

Revision ID: 518343af8634
Revises: f2b973f3f92b
Create Date: 2024-04-04 18:27:28.337817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518343af8634'
down_revision = 'f2b973f3f92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
